#!/usr/bin/env php
<?php

error_reporting(E_ALL & ~E_NOTICE);
require __DIR__ . '/../framework.php';

define('APPPATH', __DIR__);

App::init(
    array(
         'classpath' => APPPATH . '/src',
    )
);

Route::on('', function(){
    Controller::factory('\Example\Controller\Cli\Help');
});

Route::on('404', function()
{
    Controller::factory('\Example\Controller\Cli\Unknown');
});

Route::on('debug', function()
{
    echo '[Debug mode] args:' . PHP_EOL;
    print_r(func_get_args());
});

Route::on('help', function()
{
    print 'debug   To debug system
404     Show 404 output
test    To test application
server  To show server environments';
});

Route::on('server', function(){
    print_r($_SERVER);
});

Event::on(EVENT_SHUTDOWN, function(){
   print '

copyright (c) 2011-2012 Omniapp framework.
';
});

Event::on(EVENT_RUN, function(){
    print 'Welcome to omniapp cli mode:

';
});

App::run();